export const DEMO_TENANT_ID = "demo_sahaay_home_services";

export const demoTenant = {
  tenantId: DEMO_TENANT_ID,
  name: "Sahaay Home Services",
  city: "Mumbai",
  defaultWorkerLanguage: "hi-IN",
  supportedCustomerLanguages: ["en-IN", "hi-IN"],
  policyPackVersion: "taskconfirm-demo-v1",
};

export const demoWorker = {
  publicUserId: "demo-worker-asha",
  tenantId: DEMO_TENANT_ID,
  role: "WORKER" as const,
  displayName: "Asha",
  locale: "hi-IN",
  status: "ACTIVE" as const,
};

export const demoBooking = {
  bookingKey: "DEMO-4821",
  tenantId: DEMO_TENANT_ID,
  workerPublicUserId: demoWorker.publicUserId,
  customerAlias: "Neha",
  serviceId: "essential_home_cleaning",
  serviceName: "Essential Home Cleaning",
  status: "IN_PROGRESS" as const,
  city: "Mumbai",
  workerRole: "cleaning_specialist",
  currency: "INR" as const,
  scheduledDurationMinutes: 60,
  remainingDurationMinutes: 40,
  version: 1,
  includedTaskIds: [
    "kitchen_surface_cleaning",
    "bathroom_cleaning_standard_1",
    "floor_cleaning_standard",
  ],
  existingAddOnTaskIds: [] as string[],
  catalogVersion: "task-catalog-v1",
};

const task = (
  taskId: string,
  displayName: string,
  category: string,
  riskTier: number,
  synonymsHi: string[],
  synonymsMr: string[],
) => ({
  tenantId: DEMO_TENANT_ID,
  catalogVersion: "task-catalog-v1",
  taskId,
  displayName,
  category,
  riskTier,
  synonymsHi,
  synonymsMr,
  active: true,
});

export const demoTasks = [
  task(
    "kitchen_surface_cleaning",
    "Kitchen surface cleaning",
    "cleaning",
    1,
    ["किचन साफ करना"],
    ["स्वयंपाकघर पृष्ठभाग साफ"],
  ),
  task(
    "bathroom_cleaning_standard_1",
    "One standard bathroom",
    "cleaning",
    1,
    ["एक बाथरूम", "bathroom cleaning"],
    ["एक बाथरूम साफ करणे"],
  ),
  task(
    "floor_cleaning_standard",
    "Standard floor cleaning",
    "cleaning",
    1,
    ["फ्लोर साफ करना", "पोछा"],
    ["फरशी साफ करणे"],
  ),
  task(
    "balcony_deep_cleaning",
    "Balcony deep cleaning",
    "deep_cleaning",
    1,
    ["बालकनी डीप क्लीन", "balcony scrub"],
    ["बाल्कनी डीप क्लीन"],
  ),
  task(
    "inside_cabinet_cleaning",
    "Inside-cabinet cleaning",
    "deep_cleaning",
    1,
    ["कैबिनेट के अंदर साफ"],
    ["कॅबिनेट आतून साफ"],
  ),
  task(
    "wardrobe_assembly",
    "Wardrobe assembly",
    "assembly",
    2,
    ["अलमारी जोड़ना"],
    ["वॉर्डरोब जोडणे"],
  ),
  task(
    "exposed_live_wire_response",
    "Exposed live wire near work area",
    "electrical_safety",
    3,
    ["खुला बिजली का तार", "live wire"],
    ["उघडी वीज वायर"],
  ),
];

export const demoPolicySource = {
  tenantId: DEMO_TENANT_ID,
  sourceKey: "taskconfirm-demo-policy",
  title: "Sahaay Home Services Demonstration Task and Add-on Policy",
  owner: "Demo Operations Owner",
  version: "v1",
  status: "ACTIVE" as const,
  effectiveFrom: "2026-08-31T00:00:00.000Z",
  effectiveTo: null,
  priority: 100,
  regionTags: ["Mumbai"],
  roleTags: ["cleaning_specialist"],
  notice: "Fictional demonstration policy; not a real operator policy.",
};

export const demoPolicyPassages = [
  [
    "included-standard-bathroom",
    "Included work",
    "One standard bathroom is included in the Essential Home Cleaning booking.",
  ],
  [
    "balcony-deep-clean-add-on",
    "Balcony add-on",
    "Balcony deep cleaning is an optional add-on requiring customer approval. It adds 25 minutes and costs ₹299.",
  ],
  [
    "cabinet-clean-tradeoff",
    "Task trade-off",
    "Inside-cabinet cleaning may replace standard floor cleaning when the customer confirms the trade-off.",
  ],
  [
    "wardrobe-not-supported",
    "Unsupported task",
    "Wardrobe assembly is not provided under Essential Home Cleaning.",
  ],
  [
    "exposed-wire-escalation",
    "Electrical safety",
    "Stop affected work near an exposed live wire and contact a supervisor for safety review.",
  ],
].map(([passageKey, heading, text], sectionOrder) => ({
  tenantId: DEMO_TENANT_ID,
  sourceKey: demoPolicySource.sourceKey,
  sourceVersion: demoPolicySource.version,
  passageKey: passageKey!,
  heading: heading!,
  text: text!,
  sectionOrder,
  createdAt: "2026-08-31T00:00:00.000Z",
}));

const baseRule = {
  tenantId: DEMO_TENANT_ID,
  sourceKey: demoPolicySource.sourceKey,
  sourceVersion: demoPolicySource.version,
  ruleVersion: "v1",
  catalogVersion: demoBooking.catalogVersion,
  currency: demoBooking.currency,
  active: true,
  effectiveFrom: demoPolicySource.effectiveFrom,
  effectiveTo: null,
  priority: 100,
  serviceId: demoBooking.serviceId,
  requiresCustomerRequestConfirmation: true,
  requiresCustomerCommercialApproval: false,
  requiresHumanReview: false,
  requiresWorkerFeasibilityConfirmation: false,
  roleTags: ["cleaning_specialist"],
  regionTags: ["Mumbai"],
  specificity: 2,
  removableTaskIds: [] as string[],
  prohibitedActions: ["CANCEL_BOOKING"],
};

export const demoPolicyRules = [
  {
    ...baseRule,
    ruleKey: "included-standard-bathroom",
    passageKey: "included-standard-bathroom",
    taskId: "bathroom_cleaning_standard_1",
    decisionState: "INCLUDED_CONTINUE" as const,
    durationDeltaMinutes: 0,
    priceDeltaMinor: 0,
    requiresCustomerRequestConfirmation: false,
  },
  {
    ...baseRule,
    ruleKey: "balcony-deep-clean-add-on",
    passageKey: "balcony-deep-clean-add-on",
    taskId: "balcony_deep_cleaning",
    decisionState: "ADD_ON_APPROVAL_REQUIRED" as const,
    durationDeltaMinutes: 25,
    priceDeltaMinor: 29_900,
    requiresCustomerCommercialApproval: true,
  },
  {
    ...baseRule,
    ruleKey: "cabinet-clean-tradeoff",
    passageKey: "cabinet-clean-tradeoff",
    taskId: "inside_cabinet_cleaning",
    decisionState: "TRADE_OFF_REQUIRED" as const,
    durationDeltaMinutes: 0,
    priceDeltaMinor: 0,
    removableTaskIds: ["floor_cleaning_standard"],
    requiresWorkerFeasibilityConfirmation: true,
  },
  {
    ...baseRule,
    ruleKey: "wardrobe-not-supported",
    passageKey: "wardrobe-not-supported",
    taskId: "wardrobe_assembly",
    decisionState: "NOT_SUPPORTED" as const,
    durationDeltaMinutes: 0,
    priceDeltaMinor: 0,
  },
  {
    ...baseRule,
    ruleKey: "exposed-wire-escalation",
    passageKey: "exposed-wire-escalation",
    taskId: "exposed_live_wire_response",
    decisionState: "SAFETY_ESCALATION" as const,
    durationDeltaMinutes: 0,
    priceDeltaMinor: 0,
    requiresHumanReview: true,
  },
];
