import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  tenants: defineTable({
    tenantId: v.string(),
    name: v.string(),
    city: v.string(),
    defaultWorkerLanguage: v.string(),
    supportedCustomerLanguages: v.array(v.string()),
    policyPackVersion: v.string(),
  }).index("by_tenant_id", ["tenantId"]),
  users: defineTable({
    publicUserId: v.string(),
    tenantId: v.string(),
    role: v.literal("WORKER"),
    displayName: v.string(),
    locale: v.string(),
    status: v.literal("ACTIVE"),
  }).index("by_tenant_public_user", ["tenantId", "publicUserId"]),
  bookings: defineTable({
    bookingKey: v.string(),
    tenantId: v.string(),
    workerPublicUserId: v.string(),
    customerAlias: v.string(),
    serviceId: v.string(),
    serviceName: v.string(),
    status: v.literal("IN_PROGRESS"),
    city: v.string(),
    currency: v.literal("INR"),
    scheduledDurationMinutes: v.number(),
    version: v.number(),
    includedTaskIds: v.array(v.string()),
    existingAddOnTaskIds: v.array(v.string()),
    catalogVersion: v.string(),
  }).index("by_tenant_booking_key", ["tenantId", "bookingKey"]),
  taskCatalog: defineTable({
    tenantId: v.string(),
    catalogVersion: v.string(),
    taskId: v.string(),
    displayName: v.string(),
    category: v.string(),
    riskTier: v.number(),
    synonymsHi: v.array(v.string()),
    synonymsMr: v.array(v.string()),
    active: v.boolean(),
  }).index("by_tenant_task", ["tenantId", "taskId"]),
  policySources: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    title: v.string(),
    owner: v.string(),
    version: v.string(),
    status: v.literal("ACTIVE"),
    effectiveFrom: v.string(),
    regionTags: v.array(v.string()),
    roleTags: v.array(v.string()),
    notice: v.string(),
  }).index("by_tenant_source_version", ["tenantId", "sourceKey", "version"]),
  policyRules: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    sourceVersion: v.string(),
    ruleKey: v.string(),
    taskId: v.string(),
    serviceId: v.string(),
    decisionState: v.union(
      v.literal("INCLUDED_CONTINUE"),
      v.literal("ADD_ON_APPROVAL_REQUIRED"),
      v.literal("TRADE_OFF_REQUIRED"),
      v.literal("NOT_SUPPORTED"),
      v.literal("SAFETY_ESCALATION"),
    ),
    durationDeltaMinutes: v.number(),
    priceDeltaMinor: v.number(),
    requiresCustomerRequestConfirmation: v.boolean(),
    requiresCustomerCommercialApproval: v.boolean(),
    requiresHumanReview: v.boolean(),
    removableTaskIds: v.array(v.string()),
  }).index("by_tenant_rule", ["tenantId", "ruleKey"]),
  demoRuns: defineTable({
    tenantId: v.string(),
    publicRunId: v.string(),
    browserTokenHash: v.string(),
    status: v.union(
      v.literal("ACTIVE"),
      v.literal("ABANDONED"),
      v.literal("COMPLETED"),
    ),
    bookingKey: v.string(),
    startedAt: v.string(),
    lastActiveAt: v.string(),
    resumeExpiresAt: v.string(),
    abandonedAt: v.optional(v.string()),
  })
    .index("by_tenant_public_run", ["tenantId", "publicRunId"])
    .index("by_resume_expiry", ["resumeExpiresAt"]),
  incidents: defineTable({
    incidentKey: v.string(),
    tenantId: v.string(),
    demoRunId: v.id("demoRuns"),
    scenarioPack: v.literal("TASK_CONFIRM"),
    bookingKey: v.string(),
    bookingVersion: v.number(),
    workerPublicUserId: v.string(),
    status: v.union(
      v.literal("DRAFT"),
      v.literal("INPUT_CAPTURED"),
      v.literal("TRANSCRIPT_READY"),
      v.literal("TRANSCRIPT_CONFIRMED"),
      v.literal("TASK_CONFIRMATION_REQUIRED"),
      v.literal("TASK_CONFIRMED"),
      v.literal("AWAITING_HUMAN_REVIEW"),
    ),
    riskTier: v.number(),
    supportState: v.string(),
    flowVersion: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_tenant_incident_key", ["tenantId", "incidentKey"])
    .index("by_tenant_booking", ["tenantId", "bookingKey"]),
  traceSteps: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    runId: v.id("demoRuns"),
    sequence: v.number(),
    stage: v.string(),
    actor: v.string(),
    status: v.literal("COMPLETED"),
    inputSummary: v.string(),
    outputSummary: v.string(),
    sourceIds: v.array(v.string()),
    flowVersion: v.string(),
    startedAt: v.string(),
    completedAt: v.string(),
    metadata: v.object({ bookingVersion: v.number() }),
  })
    .index("by_tenant_incident_sequence", ["tenantId", "incidentId", "sequence"])
    .index("by_run_sequence", ["runId", "sequence"]),
  mediaInputs: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    modality: v.union(v.literal("TEXT"), v.literal("PRESET")),
    capturePurpose: v.literal("CUSTOMER_REQUESTED_CHANGE"),
    consentBasis: v.literal("WORKER_INITIATED_REPORT"),
    qualityState: v.literal("USABLE"),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  transcripts: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    mediaInputId: v.id("mediaInputs"),
    provider: v.literal("TYPED_OR_REVIEWED_PRESET"),
    providerModel: v.literal("deterministic-input-v1"),
    mode: v.union(v.literal("TEXT"), v.literal("PRESET")),
    detectedLanguages: v.array(v.string()),
    rawTranscript: v.string(),
    inputQualityState: v.literal("USABLE"),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  transcriptConfirmations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    transcriptId: v.id("transcripts"),
    confirmedBy: v.string(),
    originalText: v.string(),
    confirmedText: v.string(),
    wasEdited: v.boolean(),
    editSummary: v.string(),
    confirmedAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  exceptionInterpretations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    confirmedTranscriptId: v.id("transcriptConfirmations"),
    flowVersion: v.string(),
    promptVersion: v.string(),
    modelId: v.string(),
    reportedRequest: v.string(),
    summary: v.string(),
    candidateTasks: v.array(
      v.object({
        taskId: v.string(),
        displayName: v.string(),
        matchReason: v.string(),
      }),
    ),
    shouldAbstain: v.boolean(),
    abstentionReason: v.optional(v.string()),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  taskConfirmations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    interpretationId: v.id("exceptionInterpretations"),
    selectedTaskId: v.string(),
    confirmedByWorker: v.string(),
    confirmedAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  humanReviews: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    reviewType: v.literal("TASK_MAPPING"),
    status: v.literal("OPEN"),
    reasonCode: v.string(),
    contextSnapshot: v.object({ confirmedText: v.string() }),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
});
