import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  studioUsers: defineTable({
    tenantId: v.string(), identityId: v.string(), emailHash: v.string(), displayName: v.string(),
    role: v.union(v.literal("OPERATOR"), v.literal("PLATFORM_ADMIN")), status: v.literal("ACTIVE"), createdAt: v.string(),
  }).index("by_tenant_identity", ["tenantId", "identityId"]).index("by_tenant_email_hash", ["tenantId", "emailHash"]),
  studioSignInLinks: defineTable({
    tenantId: v.string(), studioUserId: v.id("studioUsers"), tokenHash: v.string(),
    expiresAt: v.string(), consumedAt: v.optional(v.string()), createdAt: v.string(),
  }).index("by_token_hash", ["tokenHash"]).index("by_tenant_user", ["tenantId", "studioUserId"]),
  studioSessions: defineTable({
    tenantId: v.string(), studioUserId: v.id("studioUsers"), sessionTokenHash: v.string(),
    expiresAt: v.string(), revokedAt: v.optional(v.string()), createdAt: v.string(), lastActiveAt: v.string(),
  }).index("by_session_token_hash", ["sessionTokenHash"]).index("by_tenant_user", ["tenantId", "studioUserId"]),
  contactAccessEvents: defineTable({
    tenantId: v.string(), studioUserId: v.id("studioUsers"), contactId: v.id("demoContacts"),
    purpose: v.union(v.literal("RESULT_DELIVERY"), v.literal("ACCOUNT_INVITATION")), occurredAt: v.string(),
  }).index("by_tenant_contact", ["tenantId", "contactId"]).index("by_tenant_actor", ["tenantId", "studioUserId"]),
  deletionRequests: defineTable({
    tenantId: v.string(), contactId: v.id("demoContacts"), demoRunId: v.id("demoRuns"),
    requestedBy: v.string(), requestEvidence: v.string(), requestReason: v.optional(v.string()), status: v.union(v.literal("PENDING"), v.literal("APPROVED"), v.literal("UNCERTAIN"), v.literal("REFUSED"), v.literal("APPROVED_FOR_DELETION"), v.literal("DELETED")),
    dueAt: v.string(), createdAt: v.string(), updatedAt: v.string(), approvalConfirmedAt: v.optional(v.string()),
  }).index("by_tenant_status", ["tenantId", "status"]).index("by_tenant_contact", ["tenantId", "contactId"]),
  deletionReviews: defineTable({
    tenantId: v.string(), deletionRequestId: v.id("deletionRequests"), reviewerUserId: v.id("studioUsers"),
    decision: v.union(v.literal("APPROVE"), v.literal("REFUSE"), v.literal("UNCERTAIN")), reason: v.string(), reviewedAt: v.string(),
  }).index("by_tenant_request", ["tenantId", "deletionRequestId"]),
  retainedInvitations: defineTable({
    tenantId: v.string(), type: v.union(v.literal("EMAIL"), v.literal("INDIAN_MOBILE")),
    contactCiphertext: v.string(), contactIv: v.string(), contactAuthTag: v.string(), contactLookupHash: v.string(), maskedDisplay: v.string(),
    consentVersion: v.string(), consentedAt: v.string(), expiresAt: v.string(), retainedAt: v.string(),
  }).index("by_tenant_contact_hash", ["tenantId", "contactLookupHash"]).index("by_expiry", ["expiresAt"]),
  retentionReceipts: defineTable({
    tenantId: v.string(), receiptType: v.union(v.literal("EXPIRY"), v.literal("DELETION")),
    anonymousRecordCount: v.number(), completedAt: v.string(),
  }).index("by_tenant_completed", ["tenantId", "completedAt"]),
  tenants: defineTable({
    tenantId: v.string(),
    name: v.string(),
    city: v.string(),
    defaultWorkerLanguage: v.string(),
    supportedCustomerLanguages: v.array(v.string()),
    policyPackVersion: v.string(),
  }).index("by_tenant_id", ["tenantId"]),
  users: defineTable({
    publicUserId: v.string(),
    tenantId: v.string(),
    role: v.literal("WORKER"),
    displayName: v.string(),
    locale: v.string(),
    status: v.literal("ACTIVE"),
  }).index("by_tenant_public_user", ["tenantId", "publicUserId"]),
  bookings: defineTable({
    bookingKey: v.string(),
    tenantId: v.string(),
    workerPublicUserId: v.string(),
    customerAlias: v.string(),
    serviceId: v.string(),
    serviceName: v.string(),
    status: v.literal("IN_PROGRESS"),
    city: v.string(),
    currency: v.literal("INR"),
    scheduledDurationMinutes: v.number(),
    remainingDurationMinutes: v.number(),
    workerRole: v.string(),
    version: v.number(),
    includedTaskIds: v.array(v.string()),
    existingAddOnTaskIds: v.array(v.string()),
    catalogVersion: v.string(),
  }).index("by_tenant_booking_key", ["tenantId", "bookingKey"]),
  taskCatalog: defineTable({
    tenantId: v.string(),
    catalogVersion: v.string(),
    taskId: v.string(),
    displayName: v.string(),
    category: v.string(),
    riskTier: v.number(),
    synonymsHi: v.array(v.string()),
    synonymsMr: v.array(v.string()),
    active: v.boolean(),
  })
    .index("by_tenant_task", ["tenantId", "taskId"])
    .index("by_tenant_catalog", ["tenantId", "catalogVersion"]),
  policySources: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    title: v.string(),
    owner: v.string(),
    version: v.string(),
    status: v.literal("ACTIVE"),
    effectiveFrom: v.string(),
    effectiveTo: v.union(v.string(), v.null()),
    priority: v.number(),
    regionTags: v.array(v.string()),
    roleTags: v.array(v.string()),
    notice: v.string(),
  }).index("by_tenant_source_version", ["tenantId", "sourceKey", "version"]),
  policyPassages: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    sourceVersion: v.string(),
    passageKey: v.string(),
    heading: v.string(),
    text: v.string(),
    sectionOrder: v.number(),
    createdAt: v.string(),
  }).index("by_tenant_source_passage", [
    "tenantId",
    "sourceKey",
    "sourceVersion",
    "passageKey",
  ]),
  policyRules: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    sourceVersion: v.string(),
    ruleKey: v.string(),
    ruleVersion: v.string(),
    passageKey: v.string(),
    catalogVersion: v.string(),
    taskId: v.string(),
    serviceId: v.string(),
    decisionState: v.union(
      v.literal("INCLUDED_CONTINUE"),
      v.literal("ADD_ON_APPROVAL_REQUIRED"),
      v.literal("TRADE_OFF_REQUIRED"),
      v.literal("NOT_SUPPORTED"),
      v.literal("SAFETY_ESCALATION"),
    ),
    durationDeltaMinutes: v.number(),
    priceDeltaMinor: v.number(),
    currency: v.string(),
    active: v.boolean(),
    effectiveFrom: v.string(),
    effectiveTo: v.union(v.string(), v.null()),
    priority: v.number(),
    specificity: v.number(),
    regionTags: v.array(v.string()),
    roleTags: v.array(v.string()),
    requiresCustomerRequestConfirmation: v.boolean(),
    requiresCustomerCommercialApproval: v.boolean(),
    requiresHumanReview: v.boolean(),
    requiresWorkerFeasibilityConfirmation: v.boolean(),
    removableTaskIds: v.array(v.string()),
    prohibitedActions: v.array(v.string()),
  }).index("by_tenant_rule", ["tenantId", "ruleKey"]),
  demoRuns: defineTable({
    tenantId: v.string(),
    publicRunId: v.string(),
    browserTokenHash: v.string(),
    status: v.union(
      v.literal("ACTIVE"),
      v.literal("ABANDONED"),
      v.literal("COMPLETED"),
    ),
    bookingKey: v.string(),
    startedAt: v.string(),
    lastActiveAt: v.string(),
    resumeExpiresAt: v.string(),
    abandonedAt: v.optional(v.string()),
    firstCheckpointDismissedAt: v.optional(v.string()),
    secondCheckpointDismissedAt: v.optional(v.string()),
  })
    .index("by_tenant_public_run", ["tenantId", "publicRunId"])
    .index("by_resume_expiry", ["resumeExpiresAt"]),
  demoContacts: defineTable({
    tenantId: v.string(), demoRunId: v.id("demoRuns"), type: v.union(v.literal("EMAIL"), v.literal("INDIAN_MOBILE")),
    contactCiphertext: v.string(), contactIv: v.string(), contactAuthTag: v.string(), contactLookupHash: v.string(), maskedDisplay: v.string(), verificationState: v.literal("UNVERIFIED"),
    deliveryPurposeExpiresAt: v.string(), invitationConsent: v.boolean(), consentVersion: v.optional(v.string()), consentedAt: v.optional(v.string()), invitationExpiresAt: v.optional(v.string()), invitationSentAt: v.optional(v.string()), createdAt: v.string(), updatedAt: v.string(),
  }).index("by_tenant_run", ["tenantId", "demoRunId"]).index("by_tenant_contact_hash", ["tenantId", "contactLookupHash"]),
  demoResultLinks: defineTable({
    tenantId: v.string(), demoRunId: v.id("demoRuns"), contactId: v.id("demoContacts"), tokenHash: v.string(),
    resultSnapshot: v.object({ requestSummary: v.string(), policyOutcome: v.object({ decisionState: v.string(), supportState: v.string(), sourceKey: v.optional(v.string()), sourceVersion: v.optional(v.string()) }), customerDecision: v.string(), finalReceipt: v.union(v.null(), v.object({ connector: v.string(), externalActionId: v.string(), status: v.string(), executedAt: v.string() })), verificationState: v.string() }),
    expiresAt: v.string(), deleteAfter: v.string(), status: v.union(v.literal("ACTIVE"), v.literal("REVOKED")), createdAt: v.string(), updatedAt: v.string(),
  }).index("by_token_hash", ["tokenHash"]).index("by_tenant_run", ["tenantId", "demoRunId"]),
  demoDeliveries: defineTable({
    tenantId: v.string(), demoRunId: v.id("demoRuns"), contactId: v.id("demoContacts"), resultLinkId: v.id("demoResultLinks"), channel: v.union(v.literal("EMAIL"), v.literal("SMS")), status: v.union(v.literal("PENDING"), v.literal("DELIVERED"), v.literal("FAILED")), provider: v.optional(v.string()), providerMessageId: v.optional(v.string()), acceptedAt: v.optional(v.string()), errorCode: v.optional(v.string()), errorMessage: v.optional(v.string()), browserRateKey: v.string(), contactRateKey: v.string(), attemptedAt: v.string(), updatedAt: v.string(),
  }).index("by_tenant_browser_attempt", ["tenantId", "browserRateKey", "attemptedAt"]).index("by_tenant_contact_attempt", ["tenantId", "contactRateKey", "attemptedAt"]).index("by_tenant_run", ["tenantId", "demoRunId"]),
  incidents: defineTable({
    incidentKey: v.string(),
    tenantId: v.string(),
    demoRunId: v.id("demoRuns"),
    scenarioPack: v.literal("TASK_CONFIRM"),
    bookingKey: v.string(),
    bookingVersion: v.number(),
    workerPublicUserId: v.string(),
    status: v.union(
      v.literal("DRAFT"),
      v.literal("INPUT_CAPTURED"),
      v.literal("TRANSCRIPT_READY"),
      v.literal("TRANSCRIPT_CONFIRMED"),
      v.literal("TASK_CONFIRMATION_REQUIRED"),
      v.literal("TASK_CONFIRMED"),
      v.literal("DECISION_READY"),
      v.literal("AWAITING_CUSTOMER"),
      v.literal("ACTION_AUTHORISED"),
      v.literal("ACTION_EXECUTING"),
      v.literal("ACTION_EXECUTED"),
      v.literal("COMPLETION_PENDING"),
      v.literal("AWAITING_COMPLETION_RESPONSE"),
      v.literal("VERIFIED"),
      v.literal("DISPUTED"),
      v.literal("AWAITING_HUMAN_REVIEW"),
    ),
    riskTier: v.number(),
    supportState: v.string(),
    flowVersion: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_tenant_incident_key", ["tenantId", "incidentKey"])
    .index("by_tenant_booking", ["tenantId", "bookingKey"]),
  traceSteps: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    runId: v.id("demoRuns"),
    sequence: v.number(),
    stage: v.string(),
    actor: v.string(),
    status: v.literal("COMPLETED"),
    inputSummary: v.string(),
    outputSummary: v.string(),
    sourceIds: v.array(v.string()),
    flowVersion: v.string(),
    startedAt: v.string(),
    completedAt: v.string(),
    metadata: v.object({ bookingVersion: v.number() }),
  })
    .index("by_tenant_incident_sequence", [
      "tenantId",
      "incidentId",
      "sequence",
    ])
    .index("by_run_sequence", ["runId", "sequence"]),
  mediaInputs: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    modality: v.union(v.literal("TEXT"), v.literal("PRESET"), v.literal("VOICE")),
    capturePurpose: v.literal("CUSTOMER_REQUESTED_CHANGE"),
    consentBasis: v.literal("WORKER_INITIATED_REPORT"),
    qualityState: v.union(v.literal("USABLE"), v.literal("RETRY_RECOMMENDED")),
    rawAudioStorageId: v.optional(v.id("_storage")),
    rawAudioMimeType: v.optional(v.string()),
    rawAudioByteLength: v.optional(v.number()),
    rawAudioDurationMs: v.optional(v.number()),
    rawAudioExpiresAt: v.optional(v.string()),
    rawAudioDeletedAt: v.optional(v.string()),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  transcripts: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    mediaInputId: v.id("mediaInputs"),
    provider: v.string(),
    providerModel: v.string(),
    mode: v.union(v.literal("TEXT"), v.literal("PRESET"), v.literal("VOICE")),
    detectedLanguages: v.array(v.string()),
    rawTranscript: v.string(),
    inputQualityState: v.union(v.literal("USABLE"), v.literal("RETRY_RECOMMENDED")),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  transcriptConfirmations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    transcriptId: v.id("transcripts"),
    confirmedBy: v.string(),
    originalText: v.string(),
    confirmedText: v.string(),
    wasEdited: v.boolean(),
    editSummary: v.string(),
    confirmedAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  exceptionInterpretations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    confirmedTranscriptId: v.id("transcriptConfirmations"),
    flowVersion: v.string(),
    promptVersion: v.string(),
    modelId: v.string(),
    sourceId: v.optional(v.string()),
    sourceVersion: v.optional(v.string()),
    providerMetadata: v.optional(v.object({
      provider: v.string(),
      attemptCount: v.number(),
      latencyMs: v.number(),
      inputTokens: v.union(v.number(), v.null()),
      outputTokens: v.union(v.number(), v.null()),
      estimatedCostMinor: v.union(v.number(), v.null()),
      failureCode: v.union(v.string(), v.null()),
    })),
    reportedRequest: v.string(),
    summary: v.string(),
    ambiguity: v.optional(v.object({
      isAmbiguous: v.boolean(),
      missingFields: v.array(v.string()),
      conflictingClaims: v.array(v.string()),
    })),
    riskSignals: v.optional(v.array(v.string())),
    candidateTasks: v.array(
      v.object({
        taskId: v.string(),
        displayName: v.string(),
        matchReason: v.string(),
      }),
    ),
    shouldAbstain: v.boolean(),
    abstentionReason: v.optional(v.string()),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  taskConfirmations: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    interpretationId: v.id("exceptionInterpretations"),
    selectedTaskId: v.string(),
    confirmedByWorker: v.string(),
    confirmedAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  humanReviews: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    reviewType: v.union(
      v.literal("TASK_MAPPING"),
      v.literal("POLICY_SUPPORT"),
      v.literal("COMPLETION_BLOCKER"),
      v.literal("COMPLETION_DISPUTE"),
      v.literal("CAPABILITY_CHALLENGE"),
    ),
    status: v.literal("OPEN"),
    reasonCode: v.string(),
    contextSnapshot: v.object({
      confirmedText: v.string(),
      bookingVersion: v.optional(v.number()),
      taskIds: v.optional(v.array(v.string())),
    }),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  policyDecisions: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    bookingVersion: v.number(),
    taskId: v.string(),
    ruleKey: v.optional(v.string()),
    ruleVersion: v.optional(v.string()),
    sourceKey: v.optional(v.string()),
    sourceVersion: v.optional(v.string()),
    passageKey: v.optional(v.string()),
    decisionState: v.optional(
      v.union(
        v.literal("INCLUDED_CONTINUE"),
        v.literal("ADD_ON_APPROVAL_REQUIRED"),
        v.literal("TRADE_OFF_REQUIRED"),
        v.literal("NOT_SUPPORTED"),
        v.literal("SAFETY_ESCALATION"),
      ),
    ),
    supportState: v.union(
      v.literal("SUPPORTED"),
      v.literal("PARTIALLY_SUPPORTED"),
      v.literal("CANNOT_VERIFY"),
      v.literal("SOURCE_CONFLICT"),
      v.literal("ESCALATED"),
    ),
    durationDeltaMinutes: v.optional(v.number()),
    priceDeltaMinor: v.optional(v.number()),
    currency: v.optional(v.string()),
    removableTaskIds: v.array(v.string()),
    requirements: v.object({
      customerRequestConfirmation: v.boolean(),
      customerCommercialApproval: v.boolean(),
      humanReview: v.boolean(),
      workerFeasibilityConfirmation: v.boolean(),
    }),
    flowVersion: v.string(),
    promptVersion: v.string(),
    modelId: v.string(),
    allowedActions: v.array(v.string()),
    prohibitedActions: v.array(v.string()),
    explanationKey: v.string(),
    decisionHash: v.string(),
    createdAt: v.string(),
  })
    .index("by_tenant_incident", ["tenantId", "incidentId"])
    .index("by_tenant_decision_hash", ["tenantId", "decisionHash"]),
  confirmationRequests: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    decisionId: v.id("policyDecisions"),
    tokenHash: v.string(),
    completionTokenHash: v.optional(v.string()),
    expiresAt: v.string(),
    status: v.union(
      v.literal("PENDING"),
      v.literal("APPROVED"),
      v.literal("DECLINED"),
      v.literal("REQUEST_MISMATCH"),
      v.literal("EXPIRED"),
      v.literal("REVOKED"),
      v.literal("STALE"),
    ),
    requestSnapshot: v.object({
      bookingKey: v.string(),
      serviceName: v.string(),
      includedTasks: v.array(
        v.object({ taskId: v.string(), displayName: v.string() }),
      ),
      resultingTasks: v.array(
        v.object({ taskId: v.string(), displayName: v.string() }),
      ),
      taskId: v.string(),
      taskDisplayName: v.string(),
      decisionState: v.literal("ADD_ON_APPROVAL_REQUIRED"),
      durationDeltaMinutes: v.number(),
      priceDeltaMinor: v.number(),
      currency: v.string(),
      removableTaskIds: v.array(v.string()),
      sourceKey: v.string(),
      sourceTitle: v.string(),
      sourceVersion: v.string(),
    }),
    requestConfirmedByCustomer: v.boolean(),
    requestConfirmedAt: v.optional(v.string()),
    commercialResponse: v.optional(
      v.union(v.literal("APPROVE"), v.literal("DECLINE")),
    ),
    respondedAt: v.optional(v.string()),
    bookingVersion: v.number(),
    decisionHash: v.string(),
    sourceVersion: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_tenant_token_hash", ["tenantId", "tokenHash"])
    .index("by_tenant_completion_token_hash", ["tenantId", "completionTokenHash"])
    .index("by_completion_token_hash", ["completionTokenHash"])
    .index("by_tenant_incident", ["tenantId", "incidentId"])
    .index("by_tenant_decision", ["tenantId", "decisionId"])
    .index("by_expiry_status", ["expiresAt", "status"]),
  actionExecutions: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    decisionId: v.id("policyDecisions"),
    confirmationRequestId: v.id("confirmationRequests"),
    connector: v.literal("DEMONSTRATION_CONNECTOR"),
    actionType: v.literal("ADD_TASK"),
    payload: v.object({
      bookingKey: v.string(),
      taskId: v.string(),
      priceDeltaMinor: v.number(),
      durationDeltaMinutes: v.number(),
    }),
    payloadHash: v.string(),
    idempotencyKey: v.string(),
    status: v.union(
      v.literal("PENDING"),
      v.literal("SUCCEEDED"),
      v.literal("RETRYABLE_FAILED"),
      v.literal("PERMANENT_FAILED"),
      v.literal("RECONCILIATION_REQUIRED"),
    ),
    attemptCount: v.number(),
    externalActionId: v.optional(v.string()),
    priorBookingVersion: v.number(),
    resultingBookingVersion: v.optional(v.number()),
    receipt: v.optional(v.object({
      actionExecutionId: v.string(),
      connector: v.literal("DEMONSTRATION_CONNECTOR"),
      idempotencyKey: v.string(),
      externalActionId: v.string(),
      requestHash: v.string(),
      previousBookingVersion: v.number(),
      resultingBookingVersion: v.number(),
      actionType: v.literal("ADD_TASK"),
      status: v.literal("SUCCEEDED"),
      executedAt: v.string(),
    })),
    errorCode: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    startedAt: v.string(),
    completedAt: v.optional(v.string()),
    updatedAt: v.string(),
  })
    .index("by_tenant_idempotency", ["tenantId", "idempotencyKey"])
    .index("by_tenant_incident", ["tenantId", "incidentId"])
    .index("by_tenant_status", ["tenantId", "status"]),
  mockConnectorReceipts: defineTable({
    tenantId: v.string(),
    idempotencyKey: v.string(),
    requestHash: v.string(),
    receipt: v.object({
      actionExecutionId: v.string(),
      connector: v.literal("DEMONSTRATION_CONNECTOR"),
      idempotencyKey: v.string(),
      externalActionId: v.string(),
      requestHash: v.string(),
      previousBookingVersion: v.number(),
      resultingBookingVersion: v.number(),
      actionType: v.literal("ADD_TASK"),
      status: v.literal("SUCCEEDED"),
      executedAt: v.string(),
    }),
    createdAt: v.string(),
  }).index("by_tenant_idempotency", ["tenantId", "idempotencyKey"]),
  completionSummaries: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    bookingVersion: v.number(),
    agreedTasks: v.array(v.object({ taskId: v.string(), displayName: v.string() })),
    workerTaskStates: v.array(v.object({ taskId: v.string(), state: v.union(v.literal("COMPLETE"), v.literal("BLOCKED")) })),
    workerNote: v.optional(v.string()),
    submittedBy: v.string(),
    submittedAt: v.string(),
    customerResponse: v.optional(v.union(v.literal("ACKNOWLEDGE"), v.literal("RAISE_ISSUE"))),
    customerNote: v.optional(v.string()),
    respondedAt: v.optional(v.string()),
    verificationState: v.union(v.literal("CANNOT_VERIFY"), v.literal("VERIFIED"), v.literal("DISPUTED"), v.literal("REVIEW_REQUIRED")),
    reviewerRequired: v.boolean(),
    updatedAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  verificationEvents: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    completionSummaryId: v.id("completionSummaries"),
    criteriaVersion: v.literal("taskconfirm-verification-v1"),
    actor: v.union(v.literal("WORKER"), v.literal("CUSTOMER"), v.literal("SYSTEM")),
    bookingVersion: v.number(),
    evidence: v.object({
      agreedTaskIds: v.array(v.string()),
      workerTaskStates: v.array(v.object({ taskId: v.string(), state: v.union(v.literal("COMPLETE"), v.literal("BLOCKED")) })),
      receiptRequired: v.boolean(),
      receiptMatches: v.boolean(),
      customerResponse: v.optional(v.union(v.literal("ACKNOWLEDGE"), v.literal("RAISE_ISSUE"))),
    }),
    actionExecutionId: v.optional(v.id("actionExecutions")),
    state: v.union(v.literal("CANNOT_VERIFY"), v.literal("VERIFIED"), v.literal("DISPUTED"), v.literal("REVIEW_REQUIRED")),
    reviewerRequired: v.boolean(),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  replays: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    capabilityKey: v.string(),
    sourceId: v.string(),
    sourceVersion: v.string(),
    rubricVersion: v.string(),
    flowVersion: v.string(),
    generatorModelId: v.string(),
    promptVersion: v.string(),
    stimulusText: v.string(),
    retryStimulusText: v.string(),
    reviewedAudioPath: v.string(),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
  replayAttempts: defineTable({
    tenantId: v.string(),
    incidentId: v.id("incidents"),
    replayId: v.id("replays"),
    attemptNumber: v.number(),
    answer: v.string(),
    result: v.union(v.literal("RETRY_REQUIRED"), v.literal("DEMONSTRATED")),
    correction: v.optional(v.string()),
    evaluatorModelId: v.string(),
    evaluatorVersion: v.string(),
    createdAt: v.string(),
  }).index("by_tenant_replay", ["tenantId", "replayId"]),
  capabilityEvents: defineTable({
    tenantId: v.string(),
    workerPublicUserId: v.string(),
    incidentId: v.id("incidents"),
    replayId: v.id("replays"),
    capabilityKey: v.string(),
    result: v.union(v.literal("DEMONSTRATED"), v.literal("NOT_YET_DEMONSTRATED")),
    assistanceLevel: v.union(v.literal("NONE"), v.literal("ONE_RETRY")),
    sourceId: v.string(),
    sourceVersion: v.string(),
    rubricVersion: v.string(),
    flowVersion: v.string(),
    generatorModelId: v.string(),
    promptVersion: v.string(),
    evaluatorModelId: v.string(),
    evaluatorVersion: v.string(),
    privateByDefault: v.literal(true),
    challenged: v.boolean(),
    createdAt: v.string(),
  }).index("by_tenant_incident", ["tenantId", "incidentId"]),
});
