import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  tenants: defineTable({
    tenantId: v.string(),
    name: v.string(),
    city: v.string(),
    defaultWorkerLanguage: v.string(),
    supportedCustomerLanguages: v.array(v.string()),
    policyPackVersion: v.string(),
  }).index("by_tenant_id", ["tenantId"]),
  users: defineTable({
    publicUserId: v.string(),
    tenantId: v.string(),
    role: v.literal("WORKER"),
    displayName: v.string(),
    locale: v.string(),
    status: v.literal("ACTIVE"),
  }).index("by_tenant_public_user", ["tenantId", "publicUserId"]),
  bookings: defineTable({
    bookingKey: v.string(),
    tenantId: v.string(),
    workerPublicUserId: v.string(),
    customerAlias: v.string(),
    serviceId: v.string(),
    serviceName: v.string(),
    status: v.literal("IN_PROGRESS"),
    city: v.string(),
    currency: v.literal("INR"),
    scheduledDurationMinutes: v.number(),
    version: v.number(),
    includedTaskIds: v.array(v.string()),
    existingAddOnTaskIds: v.array(v.string()),
    catalogVersion: v.string(),
  }).index("by_tenant_booking_key", ["tenantId", "bookingKey"]),
  taskCatalog: defineTable({
    tenantId: v.string(),
    catalogVersion: v.string(),
    taskId: v.string(),
    displayName: v.string(),
    category: v.string(),
    riskTier: v.number(),
    synonymsHi: v.array(v.string()),
    synonymsMr: v.array(v.string()),
    active: v.boolean(),
  }).index("by_tenant_task", ["tenantId", "taskId"]),
  policySources: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    title: v.string(),
    owner: v.string(),
    version: v.string(),
    status: v.literal("ACTIVE"),
    effectiveFrom: v.string(),
    regionTags: v.array(v.string()),
    roleTags: v.array(v.string()),
    notice: v.string(),
  }).index("by_tenant_source_version", ["tenantId", "sourceKey", "version"]),
  policyRules: defineTable({
    tenantId: v.string(),
    sourceKey: v.string(),
    sourceVersion: v.string(),
    ruleKey: v.string(),
    taskId: v.string(),
    serviceId: v.string(),
    decisionState: v.union(
      v.literal("INCLUDED_CONTINUE"),
      v.literal("ADD_ON_APPROVAL_REQUIRED"),
      v.literal("TRADE_OFF_REQUIRED"),
      v.literal("NOT_SUPPORTED"),
      v.literal("SAFETY_ESCALATION"),
    ),
    durationDeltaMinutes: v.number(),
    priceDeltaMinor: v.number(),
    requiresCustomerRequestConfirmation: v.boolean(),
    requiresCustomerCommercialApproval: v.boolean(),
    requiresHumanReview: v.boolean(),
    removableTaskIds: v.array(v.string()),
  }).index("by_tenant_rule", ["tenantId", "ruleKey"]),
  demoRuns: defineTable({
    tenantId: v.string(),
    publicRunId: v.string(),
    browserTokenHash: v.string(),
    status: v.union(
      v.literal("ACTIVE"),
      v.literal("ABANDONED"),
      v.literal("COMPLETED"),
    ),
    bookingKey: v.string(),
    startedAt: v.string(),
    lastActiveAt: v.string(),
    resumeExpiresAt: v.string(),
    abandonedAt: v.optional(v.string()),
  })
    .index("by_tenant_public_run", ["tenantId", "publicRunId"])
    .index("by_resume_expiry", ["resumeExpiresAt"]),
});
