import Link from "next/link";
import { requireStudioActor } from "../auth/current-actor";
import { createFixtureStudioContactGateway } from "../contacts/studio-contact-gateway";
import { reviewDeletion } from "./actions";

export default async function StudioDeletionsPage({ searchParams }: { searchParams: Promise<{ error?: string; reviewed?: string }> }) {
  const actor = await requireStudioActor();
  const requests = await createFixtureStudioContactGateway().listDeletions(actor);
  const query = await searchParams;
  return <main className="studio-shell"><header className="studio-header"><div><p className="eyebrow">Hunar Studio · Deletion desk</p><h1>Requests due within seven days</h1><p>Approval must be confirmed before contact, consent, full runs and active result links are removed.</p></div><span className="studio-role">{actor.role === "PLATFORM_ADMIN" ? "Platform administrator" : "Demo operator"}<small>{actor.actorId}</small></span></header><nav className="studio-nav" aria-label="Studio sections"><Link href="/studio/contacts">Contacts</Link><Link aria-current="page" href="/studio/deletions">Deletion requests</Link><Link href="/studio/evals">Evaluations</Link></nav>{query.error === "distinct-reviewer" && <p className="studio-alert" role="alert">A different platform administrator must complete this second review.</p>}{query.reviewed && <p className="studio-success" role="status">Second review recorded. The request can move to confirmed deletion.</p>}<ol className="studio-deletion-list">{requests.map((request) => <li key={request.requestId}><div className="studio-deletion-date"><span>Due</span><strong>{new Date(request.dueAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", timeZone: "UTC" })}</strong></div><div><span className="studio-channel">{request.state.replaceAll("_", " ")}</span><h2>{request.maskedDisplay}</h2><p>Uncertain match · opened by {request.requestedByActorId}. Evidence and reason remain in the audit record.</p></div>{actor.role === "PLATFORM_ADMIN" ? <form action={reviewDeletion}><input name="requestId" type="hidden" value={request.requestId} /><button className="button button-navy" type="submit">Complete second review</button></form> : <span className="studio-muted-action">Administrator review required</span>}</li>)}</ol></main>;
}
