import Link from "next/link";
import { requireStudioActor } from "../auth/current-actor";
import { getStudioContactGateway } from "../contacts/studio-contact-gateway";
import { confirmAndExecuteDeletion, reviewDeletion } from "./actions";
export const dynamic = "force-dynamic";

export default async function StudioDeletionsPage({ searchParams }: { searchParams: Promise<{ error?: string; reviewed?: string }> }) {
  const actor = await requireStudioActor();
  const requests = await getStudioContactGateway().listDeletions(actor);
  const query = await searchParams;
  return <main className="studio-shell"><header className="studio-header"><div><p className="eyebrow">Hunar Studio · Deletion desk</p><h1>Requests due within seven days</h1><p>Approval must be confirmed before contact, consent, full runs and active result links are removed.</p></div><span className="studio-role">{actor.role === "PLATFORM_ADMIN" ? "Platform administrator" : "Demo operator"}<small>{actor.actorId}</small></span></header><nav className="studio-nav" aria-label="Studio sections"><Link href="/studio/contacts">Contacts</Link><Link aria-current="page" href="/studio/deletions">Deletion requests</Link><Link href="/studio/evals">Evaluations</Link></nav>{query.error && <p className="studio-alert" role="alert">The requested deletion action was not authorised.</p>}{query.reviewed && <p className="studio-success" role="status">Review recorded. Approved requests can now be confirmed before deletion.</p>}<ol className="studio-deletion-list">{requests.map((request) => <li key={request.requestId}><div className="studio-deletion-date"><span>Due</span><strong>{new Date(request.dueAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", timeZone: "UTC" })}</strong></div><div><span className="studio-channel">{request.state.replaceAll("_", " ")}</span><h2>{request.maskedDisplay}</h2><p>Opened by {request.requestedByActorId}. Evidence and reason remain in the audit record.</p></div>{actor.role === "PLATFORM_ADMIN" && request.state === "APPROVED" ? <form action={confirmAndExecuteDeletion}><input name="requestId" type="hidden" value={request.requestId} /><button className="button button-navy" type="submit">Confirm and delete</button></form> : actor.role === "PLATFORM_ADMIN" ? <form action={reviewDeletion} className="studio-form"><input name="requestId" type="hidden" value={request.requestId} /><label>Decision<select name="decision" required><option value="APPROVE">Approve</option><option value="REFUSE">Refuse</option><option value="UNCERTAIN">Needs second review</option></select></label><label>Reason<input name="reason" required /></label><button className="button button-navy" type="submit">Record review</button></form> : <span className="studio-muted-action">Administrator review required</span>}</li>)}</ol></main>;
}
