import { projectPublicTrace, type PublicTrace } from "./public-trace";

export const curatedPublicTraces = {
  included: projectPublicTrace({
    traceId: "curated-included",
    title: "Included kitchen surface cleaning",
    outcome: "The booked task continued without an extra charge.",
    scenario: "TASK_CONFIRM",
    stages: [
      {
        sequence: 1,
        label: "Request confirmed",
        actor: "WORKER",
        status: "COMPLETED",
        summary: "The worker confirmed the requested kitchen surface cleaning.",
        versions: { flow: "taskconfirm-v1" },
      },
      {
        sequence: 2,
        label: "Policy resolved",
        actor: "SYSTEM",
        status: "COMPLETED",
        summary: "The active policy lists this task as included.",
        source: { id: "taskconfirm-scope-policy", version: "1.0.0" },
        versions: { model: "reviewed-mapper-v1", flow: "taskconfirm-v1", prompt: "task-map-v1" },
        approval: { state: "NOT_REQUIRED" },
        metrics: { latencyMs: 320, inputTokens: 84, outputTokens: 24, estimatedCostMinor: 1 },
      },
      {
        sequence: 3,
        label: "Outcome recorded",
        actor: "SYSTEM",
        status: "COMPLETED",
        summary: "The original booking remained active with no price change.",
        versions: { flow: "taskconfirm-v1" },
        receipt: { state: "VERIFIED", reference: "DEMO-INCLUDED-01" },
      },
    ],
  }),
  approved: projectPublicTrace({
    traceId: "curated-approved",
    title: "Balcony deep-clean add-on",
    outcome: "The customer approved the add-on and the booking update was verified.",
    scenario: "TASK_CONFIRM",
    stages: [
      {
        sequence: 1,
        label: "Changed request confirmed",
        actor: "WORKER",
        status: "COMPLETED",
        summary: "The worker confirmed a balcony deep-clean request.",
        versions: { flow: "taskconfirm-v1" },
      },
      {
        sequence: 2,
        label: "Approval required",
        actor: "SYSTEM",
        status: "COMPLETED",
        summary: "The active source requires customer approval for this add-on.",
        source: { id: "taskconfirm-scope-policy", version: "1.0.0" },
        versions: { model: "reviewed-mapper-v1", flow: "taskconfirm-v1", prompt: "task-map-v1" },
        approval: { state: "PENDING" },
        metrics: { latencyMs: 510, inputTokens: 102, outputTokens: 31, estimatedCostMinor: 2 },
      },
      {
        sequence: 3,
        label: "Customer approved",
        actor: "CUSTOMER",
        status: "COMPLETED",
        summary: "The customer approved the exact add-on terms.",
        versions: { flow: "taskconfirm-v1" },
        approval: { state: "APPROVED", approvedBy: "CUSTOMER" },
      },
      {
        sequence: 4,
        label: "Booking update verified",
        actor: "CONNECTOR",
        status: "COMPLETED",
        summary: "The authorised booking change returned a verified receipt.",
        source: { id: "taskconfirm-scope-policy", version: "1.0.0" },
        versions: { flow: "taskconfirm-v1" },
        receipt: { state: "VERIFIED", reference: "DEMO-APPROVED-01" },
        metrics: { latencyMs: 690, estimatedCostMinor: 0 },
      },
    ],
  }),
  escalated: projectPublicTrace({
    traceId: "curated-escalated",
    title: "Unsupported appliance repair request",
    outcome: "The system abstained and sent the request for human review.",
    scenario: "TASK_CONFIRM",
    stages: [
      {
        sequence: 1,
        label: "Request confirmed",
        actor: "WORKER",
        status: "COMPLETED",
        summary: "The worker confirmed an appliance repair request.",
        versions: { flow: "taskconfirm-v1" },
      },
      {
        sequence: 2,
        label: "Unsupported request",
        actor: "SYSTEM",
        status: "ABSTAINED",
        summary: "No approved source supports appliance repair in this booking.",
        source: { id: "taskconfirm-scope-policy", version: "1.0.0" },
        versions: { model: "reviewed-mapper-v1", flow: "taskconfirm-v1", prompt: "task-map-v1" },
        metrics: { latencyMs: 470, inputTokens: 91, outputTokens: 28, estimatedCostMinor: 2 },
      },
      {
        sequence: 3,
        label: "Human review created",
        actor: "REVIEWER",
        status: "ESCALATED",
        summary: "The original booking was preserved while a reviewer checks the gap.",
        versions: { flow: "taskconfirm-v1" },
        approval: { state: "NOT_REQUIRED" },
        receipt: { state: "NOT_ATTEMPTED" },
      },
    ],
  }),
} satisfies Record<"included" | "approved" | "escalated", PublicTrace>;

export type CuratedPublicTraceId = keyof typeof curatedPublicTraces;
